# Generated by Django 2.2.6 on 2019-10-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('acs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='acs.Acs')),
            ],
        ),
    ]
